name: K6_demo

on:
  push:
    branches: main

jobs:
    k6demo:
      runs-on: ubuntu-latest
      steps: 
        - name: 'checkout to main'
          uses: actions/checkout@v3
          with:
            ref: main
        - name: 'install k6'
          uses: grafana/setup-k6-action@v1
          with:
            k6-version: '0.52.0'
        - name: 'run k6 test'
          run: bash run_k6.sh
        - name: 'Upload artifact'
          uses: actions/upload-artifact@v4.4.3
          with:
            name: 'k6 reports'
            path: './reports/report.html'
        
